services:
  # Разварачивает Kafka с SSL  
  kafka:
    #image: apache/kafka:latest
    image: bitnami/kafka:latest
    container_name: kafka
    restart: unless-stopped
    networks:
      - soc-network
    ports:
      - "9093:9093"
    env_file: .env
    environment:
      KAFKA_CLUSTER_ID: Gjsdu1T-eMCtK--X86sw

      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9092     

      # Настройки listeners
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SSL,INTERNAL:SSL,EXTERNAL:SSL
      KAFKA_CFG_LISTENERS: CONTROLLER://:9092,INTERNAL://:39093,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:39093,EXTERNAL://localhost:9093 #,EXTERNAL://192.168.13.3:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_EXTER_BROKER_LISTENER_NAME: EXTERNAL
      
      # SSL настройки - серверная аутентификация
      KAFKA_CFG_SSL_CLIENT_AUTH: none
      # пароль для приватного ключа в keystore
      KAFKA_CFG_SSL_KEY_PASSWORD: $KAFKA_SSL_KEY_PASSWORD
      # пароль для keystore kafka.keystore.jks
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: $KAFKA_SSL_KEY_PASSWORD
      # пароль для truststore kafka.truststore.jks
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: $KAFKA_SSL_KEY_PASSWORD
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: /opt/bitnami/kafka/config/certs/kafka.keystore.jks
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: /opt/bitnami/kafka/config/certs/kafka.truststore.jks
      KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      
      # Настройки кластера
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      
      # Настройки для удобства разработки
      #KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      #KAFKA_CFG_LOG_RETENTION_HOURS: 24
      #KAFKA_CFG_LOG_SEGMENT_BYTES: 1073741824
      #KAFKA_CFG_NUM_PARTITIONS: 3
      #KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
      
      # Настройки безопасности
      #KAFKA_CFG_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      #KAFKA_CFG_SUPER_USERS: User:admin
    volumes:
      - $PWD/certs/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - $PWD/certs/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
      # выполняем для корректного отображения даты с учетом временной зоны
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: 'bash -c ''printf "" > /dev/tcp/127.0.0.1/9091; exit $$?;'''
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s

  kafka-ui:
    image: kafbat/kafka-ui:main
    container_name: kafka-ui
    restart: unless-stopped
    networks:
      - soc-network
    ports:
      - 8181:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /certs/kafka.keystore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: $KAFKA_SSL_KEY_PASSWORD
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:39093
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION: /certs/kafka.truststore.jks
      KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD: $KAFKA_SSL_KEY_PASSWORD
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "" # DISABLE COMMON NAME VERIFICATION
    volumes:
      - $PWD/certs:/certs:ro
    depends_on:
      - kafka

networks:
  soc-network:
    driver: bridge