#https://habr.com/ru/articles/793050/
#https://docs.nats.io/running-a-nats-service/configuration/monitoring

services:
  nats:
    image: nats:latest
    container_name: nats-server
    restart: unless-stopped
    ports:
     - "4222:4222"
     - "6222:6222"
     - "8222:8222"
    command: "--config nats-server.conf"
    #environment:
    volumes:
      - $PWD/nats-server.conf:/etc/nats/nats-server.conf:ro
    networks:
     - internal-network

  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    container_name: nats-exporter
    restart: unless-stopped
    ports:
      - "7777:7777"
    command: "-D --addr 0.0.0.0 --port 7777 -varz \"http://nats:8222\""
    # -connz -varz -channelz -serverz -subz -healthz -routez
    networks:
      - internal-network
    depends_on:
      - nats

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "$PWD/prometheus.yml:/etc/prometheus/prometheus.yml"  
    networks:
      - internal-network
    depends_on:
      - nats
      - nats-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    #hostname: grafana
    networks:
      - internal-network
    depends_on:
      - prometheus

networks:
  internal-network:
    driver: bridge
