global:
  scrape_interval: 5s # By default, scrape targets every 5 seconds.

  external_labels:
    monitor: "nats-test-server"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nats-exporter"
    static_configs:
      - targets: ["nats-exporter:7777"]
    scrape_interval: 10s
    scrape_timeout: 5s
#  - job_name: "nats"
#    static_configs:
#      - targets: ["nats:8222"]
#    metrics_path: /varz
#    scrape_interval: 10s
