services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped
    networks:
      - soc-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # если нужно что бы kafka нормально работала у клиентов с внешних ip
      KAFKA_LISTENERS: CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:29092 # определяет список слушателей для данного инстанса и их порты
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://10.0.0.136:9092,PLAINTEXT://kafka:29092 # определяет, какие адреса слушателей будут предоставляться пользователю
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:29092 # определяет, какие адреса слушателей будут предоставляться пользователю
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      #KAFKA_LOG_DIRS: $HOME/tmp/kraft-combined-logs
    volumes:
      - $PWD/kafka-logs:/tmp/kraft-combined-logs
      # выполняем для корректного отображения даты с учетом временной зоны
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
    healthcheck:
      test: 'bash -c ''printf "" > /dev/tcp/127.0.0.1/9091; exit $$?;'''
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s

  kafka-ui:
    image: kafbat/kafka-ui:main
    container_name: kafka-ui
    restart: unless-stopped
    networks:
      - soc-network
    ports:
      - 8181:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

networks:
  soc-network:
    driver: bridge